version: 1.1
name: MinecraftInformation
main: me.sketsi.mcinfo.MCInfoMain
author: Sketsi
description: Provides various information about Enchants and Potions.
commands:  
  mc:
    aliases: [smc, mi, smi]
    description: Various commands inside.
